# Generated by Django 5.0.2 on 2024-02-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='bookmarked',
        ),
    ]
