# Generated by Django 5.0.2 on 2024-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
